# -*- mode: ruby -*-
# vi: set ft=ruby :

# note, make sure you have the following plugins installed;
# vagrant plugin install vagrant-hosts
# vagrant plugin install vagrant-pe_build
# more info, https://github.com/adrienthebo

Vagrant.configure("2") do |config|
  config.vm.provision :shell, :path => "puppet_agents.sh"

  config.vm.define "development" do |development|
    development.vm.box = "centos7-basic"
    development.vm.box_url = 'file:///Users/stef/vagrant/personal-boxes/centos7-basic/centos7-basic.box'
    development.vm.hostname = 'pe-agent-development.sc-ict.intranet'
    development.ssh.pty = true
  # Customize VM
    development.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected3", "off"]
      vb.customize ["modifyvm", :id, "--cableconnected4", "off"]
      vb.customize ["modifyvm", :id, "--cableconnected5", "off"]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]  
    end
    development.vm.provision :hosts do |provisioner|
      provisioner.add.host '192.168.33.21', ['pe-agent-development.sc-ict.intranet', 'pe-agent-development']
    end 
  end
  
  config.vm.define "test" do |test|
    test.vm.box = "centos7-basic"
    test.vm.box_url = 'file:///Users/stef/vagrant/personal-boxes/centos7-basic/centos7-basic.box'
    test.vm.hostname = 'pe-agent-test.sc-ict.intranet'
    test.ssh.pty = true
  # Customize VM
    test.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected3", "off"]
      vb.customize ["modifyvm", :id, "--cableconnected4", "off"]
      vb.customize ["modifyvm", :id, "--cableconnected5", "off"]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000] 
    end
    test.vm.provision :hosts do |provisioner|
      provisioner.add.host '192.168.33.22', ['pe-agent-test.sc-ict.intranet', 'pe-agent-test']
    end
  end

  config.vm.define "acceptance" do |acceptance|
    acceptance.vm.box = "centos7-basic"
    acceptance.vm.box_url = 'file:///Users/stef/vagrant/personal-boxes/centos7-basic/centos7-basic.box'
    acceptance.vm.hostname = 'pe-agent-acceptance.sc-ict.intranet'
    acceptance.ssh.pty = true
  # Customize VM
    acceptance.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected3", "off"]
      vb.customize ["modifyvm", :id, "--cableconnected4", "off"]
      vb.customize ["modifyvm", :id, "--cableconnected5", "off"]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000] 
    end
    acceptance.vm.provision :hosts do |provisioner|
      provisioner.add.host '192.168.33.23', ['pe-agent-acceptance.sc-ict.intranet', 'pe-agent-acceptance']
    end
  end

  config.vm.define "production" do |production|
    production.vm.box = "centos7-basic"
    production.vm.box_url = 'file:///Users/stef/vagrant/personal-boxes/centos7-basic/centos7-basic.box'
    production.vm.hostname = 'pe-agent-production.sc-ict.intranet'
    production.ssh.pty = true
  # Customize VM
    production.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected3", "off"]
      vb.customize ["modifyvm", :id, "--cableconnected4", "off"]
      vb.customize ["modifyvm", :id, "--cableconnected5", "off"]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000] 
    end
    production.vm.provision :hosts do |provisioner|
      provisioner.add.host '192.168.33.24', ['pe-agent-production.sc-ict.intranet', 'pe-agent-production']
    end
  end  
end