# -*- mode: ruby -*-
# vi: set ft=ruby :

# note, make sure you have the following plugins installed;
# vagrant plugin install vagrant-hosts
# vagrant plugin install vagrant-pe_build
# more info, https://github.com/adrienthebo

Vagrant.configure('2') do |config|
  config.vm.box                      = 'centos7-basic'
  config.vm.box_url                  = 'file:///Users/stef/vagrant/personal-boxes/centos7-basic/centos7-basic.box'
  config.ssh.pty                     = true
  config.pe_build.download_root      = 'https://s3.amazonaws.com/pe-builds/released/3.7.1'
  config.pe_build.version            = '3.7.1'
  config.pe_build.filename           = 'puppet-enterprise-3.7.1-el-7-x86_64.tar.gz'
  # Define VM
  config.vm.define 'laptop-puppet-master' do |node|
    node.vm.network :private_network, ip: '192.168.33.10'
    node.vm.network :forwarded_port, guest: 443, host: 1443
    node.vm.network :forwarded_port, guest: 8080, host: 8080
    node.vm.hostname = 'laptop-puppet-master.sc-ict.intranet'
    node.vm.synced_folder "manifests/", "/manifests"
    node.vm.provision :hosts do |provisioner|
      provisioner.add.host '192.168.33.10', ['laptop-puppet-master.sc-ict.intranet', 'laptop-puppet-master']
    end
    # Customize VM
    node.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected3", "off"]
      vb.customize ["modifyvm", :id, "--cableconnected4", "off"]
      vb.customize ["modifyvm", :id, "--cableconnected5", "off"]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]  
    end
      # Setup PE
    node.vm.provision :pe_bootstrap do |provisioner|
      provisioner.answer_file = 'answers.txt'
      provisioner.role = :master
    end
    node.vm.provision :shell, :path => "puppet_master_mono.sh"
  end
end